services:
    files:
        container_name: "rDrama"
        build:
            context: .
        volumes:
            - "./:/d"
            - "./nginx.conf:/etc/nginx/sites-enabled/1"
            - "./includes:/etc/nginx/includes"
        links:
            - "redis"
            - "postgres"
        ports:
            - "80:80"
        depends_on:
            - redis
            - postgres
        logging:
            options:
                max-size: "100k"
                max-file: "1"


    redis:
        container_name: "redis"
        image: redis
        ports:
            - "6379:6379"
        logging:
            options:
                max-size: "100k"
                max-file: "1"

    postgres:
        container_name: "postgres"
        image: postgres
        command: ["postgres"] #, "-c", "log_statement=all"]
        volumes:
            - "./schema.sql:/docker-entrypoint-initdb.d/00-schema.sql"
            - "./seed-users.sql:/docker-entrypoint-initdb.d/01-seed-users.sql"
            - "./seed-badges.sql:/docker-entrypoint-initdb.d/02-seed-badges.sql"
            - "./seed-hats.sql:/docker-entrypoint-initdb.d/03-seed-hats.sql"
            - "./seed-emojis.sql:/docker-entrypoint-initdb.d/04-seed-emojis.sql"
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - "5432:5432"
        logging:
            options:
                max-size: "100k"
                max-file: "1"

    opera-proxy:
        container_name: "opera-proxy"
        image: yarmak/opera-proxy
        ports:
            - "18080:18080"
        logging:
            options:
                max-size: "100k"
                max-file: "1"
